mysite/blog/urls.py
from django.urls import path

from . import views

# define the urls (for each of the views)
app_name = 'blog'
urlpatterns = [
  # ex: /polls/
  path('home', views.home, name='home'),
  path('about', views.about, name='about'),
  path('blogs', views.blogs, name='blogs'),
  path('blogs/<int:blog_id>/', views.blog_post, name='blog_post'),
  path('whatwedo', views.whatwedo, name='whatwedo'),
  path('ourteam', views.ourteam, name='ourteam'),
  path('sponsors', views.sponsors, name='sponsors'),
  path('events', views.events, name='events'),
  path('currentevents', views.currentevents, name='currentevents'),
  path('pastevents', views.pastevents, name='pastevents'),
  path('bitsamag', views.bitsamag, name='bitsamag'),
  path('getinvolved', views.getinvolved, name='getinvolved'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings # new
from django.conf.urls.static import static # new
from blog import views as main_views

urlpatterns = [
    path('', main_views.home),
    path('', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
import datetime

from django.db import models
from django.utils import timezone

EVENT_STATUS = (
    ('CURRENT','Current'),
    ('PAST', 'Past'),
)

PORTFOLIO = (
  ('SOCIAL', 'Social'),
  ('EDUCATION', 'Education'),
  ('CAREERS','Careers'),
  ('GENERAL','General')
)

# Create your models here.
class Blog(models.Model):
  blog_title = models.CharField(max_length=200, default = 'blah')
  description_text = models.CharField(max_length=500)
  pub_date = models.DateField('date published')
  image = models.ImageField(upload_to='images/')
  blog_content = models.TextField(max_length=100000)
  
  def __str__(self):
    return '%s - %s' % (self.blog_title, self.pub_date)

class Profile(models.Model):
  position = models.CharField(max_length=200)
  name = models.CharField(max_length=500)
  image = models.ImageField(upload_to='images/profile')
  year = models.CharField(max_length=4)
  email = models.EmailField(max_length=500, null=True)
  degree = models.CharField(max_length=500, null=True)
  hobby = models.CharField(max_length=500, null=True)
  one_word = models.CharField(max_length=500, null=True)
  linkedin = models.CharField(max_length=1000, null=True)
  
  def __str__(self):
    return '%s - %s - %s' % (self.name, self.year, self.position)

class Sponsor(models.Model):
  sponsor = models.CharField(max_length=500)
  image = models.ImageField(upload_to='images/sponsor')
  description = models.TextField(max_length=1000)
  link = models.URLField(max_length=1000)
  type_of_sponsor = models.CharField(max_length=500, null=True)
  
  def __str__(self):
    return self.sponsor

class Events(models.Model):
  title = models.CharField(max_length=200)
  date = models.DateField('date of event')
  time = models.CharField(max_length=8)
  location = models.CharField(max_length=200)
  cover_photo = models.ImageField(upload_to='images/events')
  description = models.TextField(max_length=1000)
  link = models.URLField(max_length=1000)
  current_or_past = models.CharField(max_length=250, null=False, choices=EVENT_STATUS, default='CURRENT')
  portfolio = models.CharField(max_length=250, null=False, choices=PORTFOLIO, default='GENERAL')


  def __str__(self):
    return '%s - %s - %s' % (self.title, self.current_or_past, self.date)


#1. Makemigrations blog i.e. python manage.py makemigrations blog
#2. SQL migrate blog with sequence number i.e. python manage.py sqlmigrate blog 0001
#3. Migrate i.e. python manage.py migrate

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.template.defaultfilters import linebreaksbr
from django.template.defaultfilters import linebreaks
from .models import Blog, Profile, Sponsor, Events

# Create your views here.
#def index(request):
#  blogs = get_list_or_404(Blog)
#  return render(request, 'blog/index.html',{'blogs':blogs})
def home(request):
  title = "Home"
  return render(request, 'blog/index.html', {'title':title})

def about(request):
  title = "About"
  page_area = "page-area-wwd"
  return render(request, 'blog/whatwedo.html', {'title':title, 'page area':page_area})

def blogs(request):
  blogs = get_list_or_404(Blog)
  title = "Blogs"
  page_area = "page-area-ob"
  return render(request, 'blog/blogs.html', {'blogs':blogs,
    'title':title,
    'page_area':page_area
  })

def blog_post(request, blog_id):
  blog = get_object_or_404(Blog, pk=blog_id)
  blog_formatted = linebreaksbr(blog.blog_content)
  title = blog.blog_title
  page_area = "page-area-ob"
  return render(request, 'blog/blog_post.html', {'blog':blog, 'title':title, 'blog_formatted':blog_formatted, 'page_area':page_area})

def whatwedo(request):
  title = "What we do"
  page_area = "page-area-wwd"
  return render(request, 'blog/whatwedo.html', {'title':title,'page_area':page_area})
  
def ourteam(request):
  title = "Our team"
  profiles_2018 = get_list_or_404(Profile.objects.order_by('id'), year="2018")
  profiles_2019 = get_list_or_404(Profile.objects.order_by('id'), year="2019")
  profiles_2020 = get_list_or_404(Profile.objects.order_by('id'), year="2020")
  page_area = "page-area-ot"
  return render(request, 'blog/ourteam.html', {
'title':title, 
'profiles_2018':profiles_2018, 
'profiles_2019':profiles_2019, 
'profiles_2020':profiles_2020,
'page_area':page_area
})

def sponsors(request):
  title = "Sponsors"
  principal_sponsors = get_list_or_404(Sponsor, type_of_sponsor="Principal Sponsor")
  major_sponsors = get_list_or_404(Sponsor, type_of_sponsor="Major Sponsor")
  supporting_sponsors = get_list_or_404(Sponsor, type_of_sponsor="Supporting Sponsor")
  affiliated_with = get_list_or_404(Sponsor, type_of_sponsor="Affiliated With")
  page_area = "page-area-sponsors"
  return render(request, 'blog/sponsors.html', {
    'title':title, 
    'principal_sponsors':principal_sponsors,
    'major_sponsors':major_sponsors,
    'supporting_sponsors':supporting_sponsors,
    'affiliated_with':affiliated_with,
    'page_area':page_area
    })

def events(request):
  title = "Current Events"
  page_area = "page-area-ce"
  all_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT")  
  social_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="SOCIAL")  
  education_c_events= Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="EDUCATION")  
  careers_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="CAREERS")  
  return render(request, 'blog/currentevents.html', {
    'title':title,
    'page_area':page_area,
    'all_c_events':all_c_events,
    'social_c_events': social_c_events,
    'education_c_events': education_c_events,
    'careers_c_events': careers_c_events
    })

def currentevents(request):
  title = "Current Events"
  page_area = "page-area-ce"
  all_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT")  
  social_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="SOCIAL")  
  education_c_events= Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="EDUCATION")  
  careers_c_events = Events.objects.order_by('date').filter(current_or_past="CURRENT", portfolio="CAREERS")  
  return render(request, 'blog/currentevents.html', {
    'title':title,
    'page_area':page_area,
    'all_c_events':all_c_events,
    'social_c_events': social_c_events,
    'education_c_events': education_c_events,
    'careers_c_events': careers_c_events
    })

def pastevents(request):
  title = "Past Events"
  page_area = "page-area-pe"
  all_p_events = Events.objects.order_by('-date').filter(current_or_past="PAST")  
  social_p_events = Events.objects.order_by('-date').filter(current_or_past="PAST", portfolio="SOCIAL")  
  education_p_events= Events.objects.order_by('-date').filter(current_or_past="PAST", portfolio="EDUCATION")  
  careers_p_events = Events.objects.order_by('-date').filter(current_or_past="PAST", portfolio="CAREERS")  
  return render(request, 'blog/pastevents.html', {
    'title':title,
    'page_area':page_area,
    'all_p_events':all_p_events,
    'social_p_events': social_p_events,
    'education_p_events': education_p_events,
    'careers_p_events': careers_p_events
    })

def bitsamag(request):
  title = "Bitsa Mag"
  page_area = "page-area-bmag"
  return render(request, 'blog/bitsamag.html', {'title':title,'page_area':page_area})

def getinvolved(request):
  title = "Get Involved"
  page_area = "page-area-gi"
  return render(request, 'blog/getinvolved.html', {'title':title,'page_area':page_area})

mysite/blog/templates/blog/bitsamag.html
{% extends 'blog/navbar.html' %}
{% block content %}
<title>BITSA | Magazine</title>
<div class="portfolio-area area-padding">
    <div class="container">
        <div class="profilerow">
            <div class="row">
                <div class="awesome-project fix">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="awesome-menu ">
                            <ul class="portfolio-menu">
                                <li><a href="#" class="active" data-filter=".2019">2019</a></li>
                                <li><a href="#" data-filter=".2018">2018</a></li>
                                <li><a href="#" data-filter=".2017">2017</a></li>
                                <li><a href="#" data-filter=".2016">2016</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Start Description area -page -->
        <div class="section-head text-center">
            <div class="BITSA-mag">
                <div class="2019">
                    <h3>2019</h3>
                    <div class="bitsa-mag-desktop">
                        <iframe
                            src="https://drive.google.com/file/d/11VgmnHfK0hHV4LvVmQRItjjItrYztLWv/preview?usp=embed_googleplus"
                            style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
                            allowfullscreen></iframe>
                        <!-- <h1 style="padding-bottom: 20px"> Coming Soon! </h1> -->
                    </div>
                    <div class="bitsa-mag-mobile">
                        <a href="https://drive.google.com/file/d/11VgmnHfK0hHV4LvVmQRItjjItrYztLWv/view" class="mag-btn" target="_blank">Click Here!</a>
                    </div>
                </div>
                <div class="2018">
                    <h3>2018</h3>
                    <div class="bitsa-mag-desktop">
                        <iframe
                            src="https://drive.google.com/file/d/1cs04_QTzHZcwSRrDFb9CBxjZD5_PjZ2z/preview?usp=embed_googleplus"
                            style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
                            allowfullscreen></iframe>
                    </div>
                    <div class="bitsa-mag-mobile">
                        <a href="https://drive.google.com/file/d/1cs04_QTzHZcwSRrDFb9CBxjZD5_PjZ2z/view" class="mag-btn" target="_blank">Click Here!</a>
                    </div>
                </div>
                <div class="2017">
                        <h3>2017</h3>
                        <div class="bitsa-mag-desktop">
                            <iframe
                                src="https://drive.google.com/file/d/1NUjbTadvs4ixrR5Hh1ec_FlMDHVB04rI/preview?usp=embed_googleplus"
                                style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
                                allowfullscreen></iframe>
                        </div>
                        <div class="bitsa-mag-mobile">
                            <a href="https://drive.google.com/file/u/2/d/1NUjbTadvs4ixrR5Hh1ec_FlMDHVB04rI/view" class="mag-btn" target="_blank">Click Here!</a>
                        </div>
                    </div>
                    <div class="2016">
                        <h3>2016</h3>
                        <div class="bitsa-mag-desktop">
                            <iframe
                                src="https://drive.google.com/file/d/18Mca046A33Sm6fYVPWjoptXhbIvKFjlH/preview?usp=embed_googleplus"
                                style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
                                allowfullscreen></iframe>
                        </div>
                        <div class="bitsa-mag-mobile">
                            <a href="https://drive.google.com/file/d/18Mca046A33Sm6fYVPWjoptXhbIvKFjlH/view" class="mag-btn" target="_blank">Click Here!</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/blog_post.html
{% extends 'blog/navbar.html' %}
{% block content %}
<title>BITSA | {{title}}</title>
<div class="content-area blog-post-padding">
    <h1 class="blog-post-title">{{title}}</h1>
    <img src="{{ blog.image.url }}" alt="" class="blog-post-pic">
    <p class="blog-post-author">Published & Editied with care & love by the BITSA Publications Team &#x2764 </p>
    <p class="blog-post-content">{{ blog_formatted }}</p>
    <a href="{% url 'blog:blogs' %}">
        <button class="btn btn-primary slide-btn slide-submit blog-post-btn">Go Back!</button>
      </a>
</div>
{% endblock %}

mysite/blog/templates/blog/blogs.html
{% extends 'blog/navbar.html' %}
{% block content %}
<title>BITSA | Our Blog</title>
<!-- Start description Area -->
<div class="portfolio-area area-padding">
  <div class="container">
    <!-- Start Description area -page -->
    <div class="blog-section-head text-center">
      <ul>
        <h1>Welcome to the BITSA blog!</h1>
        <div class="blog_post">
          {% for blog_post in blogs reversed%}
          {% load static %}
          <div class="row blog-row">
            <div class="col-md-2 blog-col">
              <div class="blog-date-parent">
                <div class="blog-date-child">
                  <img class="blog-date-icon" src="{% static 'blog/img/blog/calendar.png' %}" alt="" />
                  <p class="blog-date">{{blog_post.pub_date}}</p>
                </div>
              </div>
            </div>
            <div class="col-md-4 blog-col">
              <a class="blog-pic-parent" href="{% url 'blog:blog_post' blog_post.id %}">
                <img src="{{ blog_post.image.url }}" alt="" class="blog-pic">
              </a>
            </div>
            <div class="col-md-6 blog-col">
              <div class="blog-date-parent">
                <div class="blog-date-child">
                  <a href="{% url 'blog:blog_post' blog_post.id %}">
                    <h1>
                      <li class="blog-title">{{blog_post.blog_title}}</li>
                    </h1>
                  </a>
                  <!-- <p>{{blog_post.description_text}}</p> -->
                  <p>{{ blog_post.blog_content|truncatewords:20 }}</p>
                  <a href="{% url 'blog:blog_post' blog_post.id %}">
                    <button class="btn btn-primary slide-btn slide-submit blog-btn">Read More</button>
                  </a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/navbar.html' %}
{% block content %}
<title>BITSA | Home</title>
<!-- Start description Area -->
{% endblock %}

mysite/blog/templates/blog/navbar.html
{% load static %}
<head>
<!-- all css here -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- bootstrap v3.3.6 css -->
<link rel="stylesheet" href="{% static 'blog/bootstrap.min.css' %}">
<!-- meanmenu css -->
<link rel="stylesheet" href="{% static 'blog/meanmenu.min.css' %}">
<!-- owl-carousel css -->
<link rel="stylesheet" href="{% static 'blog/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'blog/owl.transitions.css' %}">
<!-- font-awesome css -->
<link rel="stylesheet" href="{% static 'blog/font-awesome.min.css' %}">
  <!-- Icon css -->
<link rel="stylesheet" href="{% static 'blog/icon.css' %}">
<!-- venobox css -->
<link rel="stylesheet" href="{% static 'blog/venobox.css' %}">
<!-- responsive css -->
<link rel="stylesheet" href="{% static 'blog/style.css' %}">
<link rel="stylesheet" href="{% static 'blog/responsive.css' %}">
<!-- Favicon Link -->
<link rel="shortcut icon" href="{% static 'blog/img/logo/favicon.ico' %}" type="image/x-icon" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Meta Stuff -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div id="preloader"></div>
    <header>
        <!-- header-area start -->
        <div id="sticker" class="header-area default-header hidden-xs">
            <div class="container">
                <div class="row">
                    <!-- logo start -->
                    <div class="col-md-3 col-sm-3">
                        <div class="logo">
                            <!-- Brand -->
                            <a class="navbar-brand page-scroll sticky-logo" href="home">
                                <img src="{% static 'blog/img/logo/logowhitenarrower.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- logo end -->
                    <div class="col-md-9 col-sm-9">
                        <div class="header-right-link">
                        </div>
                        <!-- mainmenu start -->
                        <nav class="navbar navbar-default">
                            <div class="collapse navbar-collapse" id="navbar-example">
                                <div class="main-menu">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a class="pagess" href="{% url 'blog:home' %}">Home</a></li>
                                        <li><a class="pagess" href="{% url 'blog:whatwedo' %}">About Us</a>
                                        <ul class="sub-menu">
                                                <li><a href="{% url 'blog:whatwedo' %}">What We Do</a></li>
                                                <li><a href="{% url 'blog:ourteam' %}">Our Team</a></li>
                                            </ul>
                                        <li><a href="{% url 'blog:sponsors' %}">Sponsors</a></li>
                                        <li><a class="pagess" href="{% url 'blog:events' %}">Events</a>
                                            <ul class="sub-menu">
                                                <li><a href="{% url 'blog:currentevents' %}">Current Events</a></li>
                                                <li><a href="{% url 'blog:pastevents' %}">Past Events</a></li>
                                                
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'blog:blogs' %}">Our Blog</a></li>
                                        <li><a href="{% url 'blog:bitsamag' %}">Bitsa Mag</a></li>
                                        <li><a href="{% url 'blog:getinvolved' %}">Get Involved</a></li>
                                        </li>
                                        <!--<li><a href="blog.html">OUR BLOG</a></li>-->
                                    </ul>
                                </div>
                            </div>
                        </nav>
                        <!--Main menu end-->
                    </div>
                </div>
            </div>
        </div>
        <!-- header-area end -->
        <!-- mobile-menu-area start -->
        <div class="mobile-menu-area hidden-lg hidden-md hidden-sm">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="mobile-menu">
                            <div class="logo">
                                <a href="{% url 'blog:home' %}"><img src="{% static 'blog/img/logo/mobilelogoblack.png' %}" alt="" /></a>
                            </div>
                            <nav id="dropdown">
                                <ul>
                                    <li><a class="pagess" href="{% url 'blog:home' %}">Home</a> </li>
                                        <li><a href="#">About Us</a>
                                            <ul class="sub-menu">
                                                <li><a href="{% url 'blog:whatwedo' %}">What We Do</a></li>
                                                <li><a href="{% url 'blog:ourteam' %}">Our Team</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'blog:sponsors' %}">Sponsors</a></li>
                                        <li><a class="pagess" href="#">Events</a>
                                            <ul class="sub-menu">
                                                <li><a href="{% url 'blog:currentevents' %}">Current Events</a></li>
                                                <li><a href="{% url 'blog:pastevents' %}">Past Events</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'blog:blogs' %}">Our Blog</a></li>
                                        <li><a href="{% url 'blog:bitsamag' %}">Bitsa Mag</a></li>
                                        <li><a href="{% url 'blog:getinvolved' %}">Get Involved</a></li>
                                            </ul>
                                        </li>
                                </ul>
                            </nav>
                        </div>					
                    </div>
                </div>
            </div>
        </div>
        <!-- mobile-menu-area end -->
    </header>
{% if title == "Home" %}
    <!-- Start Slider Area -->
<div class="intro-area intro-default fix">
    <div class="container-full">
      <div class="row">
        <div class="intro-carousel text-center">
          <!-- Start Slider content -->
          <div class="intro-content">
            <div class="slider-img"><img src="{% static 'blog/img/background/1bitsaphotoFINAL.jpg' %}" alt="" class="slide-img"></div>
            <div class="slide-content">
              <h1 class="title1"> For all <span class="txt-rotate" data-period="2000" data-rotate='[ "tech enthusiasts.", "Infosys students."]'></span></h1>
            </div>
          </div>
          <!-- End Slider content -->
          <!-- Start Slider content -->
          <div class="intro-content ">
            <div class="slider-img">
              <img src="{% static 'blog/img/background/bitsaphoto2.jpg' %}" alt="" class="slide-img">
            </div>
  
            <div class="slide-content">
              <h1 class="title1"> Relevant <span class="txt-rotate" data-period="2000" data-rotate='[ "social events.", "workshops.", "networking opportunities."]'>
              </span></h1>
            </div>
          </div>
  <!-- End Slider content -->

  <!-- Start Slider content -->
          <div class="intro-content ">
            <div class="slider-img">
              <img src="{% static 'blog/img/background/bitsaphoto3_1.jpg' %}" alt="" class="slide-img">
            </div>
  
            <div class="slide-content">
              <h1 class="title1"> Join us on OrgSync today!</h1>
              <div class="slider-button">
                <a class="slide-btn-index" href="https://member.arc.unsw.edu.au/s/clubdetail?clubid=0016F0000371VwQQAU">JOIN NOW</a>
              </div>
  
            </div>
          </div>
  <!-- End Slider content -->
        </div>
      </div>
    </div>	 
</div>
<div class="portfolio-area area-padding">
    <div class="container">
        <div class="row">
        <!-- Start Description area -page -->
            <div class="section-head text-center">
                <h3>For Information Systems students and tech enthusiasts</h3>
        
                <p> BITSA serves to unite and empower all UNSW Information Systems students and tech enthusiasts, through actively providing an environment to share enjoyment, experiences and knowledge, to develop both academically and professionally.</p>
        
                <p> Since forming in 1988, we have been actively working to build a more cohesive community. In 2020, we are delivering more relevant events and opportunities to our members than ever before! </p>
                <div class="slider-button">
                    <a class="slide-btn" href="https://orgsync.com/81133/chapter">GET INVOLVED</a>
                </div>
    
            </div>
        </div>
    </div>
</div>
  <!-- End Slider Area -->
{% else %}  
    <div class="{{ page_area }}">
        <div class="breadcrumb-overlay"></div>
        <div class="display-table">
            <div class="display-table-cell">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcrumb text-center">
                                <div class="section-headline white-headline text-center">
                                    <h3>{{title}}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

<footer class="section">
    <!-- The container for the grid for the footer content -->
  <div class="container">
      <!-- Establishing the row in the grid for the footer content -->
    <div class="row">
        <!-- Establishing the column in the ratio 5 to 12 for Email -->
        <div class="col-md-5" id="email">
            <p id="emailP">Email - mail@bitsa.org.au </p>
        </div>
        <!-- Establishing the column in the ratio 1 to 12 for Facebook logo -->
        <div class="col-md-1">
            <section>
                <a target="_blank" class="facebook" href="https://www.facebook.com/unswissociety/">
                    <div class="fa fa-fw fa-2x fa-inverse fa-facebook"></div>
                </a>
            </section>
        </div>
        <!-- Establishing the column in the ratio 1 to 12 for Linkedin logo -->
        <div class="col-md-1">
            <section>
                <a target="_blank" class="linkedin" href="https://www.linkedin.com/company/bitsa">
                    <div class="fa fa-fw fa-2x fa-inverse fa-linkedin"></div>
                </a>
            </section>
        </div>
        <!-- Establishing the column in the ratio 5 to 12 for Address -->
        <div class="col-md-5" id="address">
            <p id="addressP">UNSW Australia </p>
        </div>
    </div>
  </div>
</footer>
  

<!-- modernizr css -->
<script src="{% static 'blog/vendor/modernizr-2.8.3.min.js' %}"></script>
<!-- jquery js -->
<script src="{% static 'blog/vendor/jquery-1.12.4.min.js' %}"></script>
<!-- Text Rotate js -->
<script src="{% static 'blog/textRotate.js' %}"></script>
<!-- bootstrap js -->
<script src="{% static 'blog/bootstrap.min.js' %}"></script>
<!-- owl-carousel js -->
<script src="{% static 'blog/owl.carousel.min.js' %}"></script>
<!-- isotope js -->
<script src="{% static 'blog/isotope.pkgd.min.js' %}"></script>
<!-- Meanmenu js -->
<script src="{% static 'blog/jquery.meanmenu.js' %}"></script>
<!-- Typed js -->
<script src="{% static 'blog/typed.js' %}"></script>
<!-- venobox js -->
<script src="{% static 'blog/venobox.min.js' %}"></script>
<!-- plugins js -->
<script src="{% static 'blog/plugins.js' %}"></script>
<!-- main js -->
<script src="{% static 'blog/main.js' %}"></script>
<!--Latest jquery version, i think the one above is outdated -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<!-- flip js convert to Django syntax-->
<script src="{% static 'blog/jquery.flip.min.js' %}"></script>
<!--logo Flip settings-->
<script>
    $(function(){
        $(".flip").flip({
            trigger: 'click'
        });
    });
</script>
</body>

mysite/blog/templates/blog/whatwedo.html
{% extends 'blog/navbar.html' %}
{% block content %}
<title>BITSA | What We Do</title>
<div class="content-area area-padding">
    <div class="container">
        <div class="row">
        <!-- Start Description area -page -->
            <div class="section-head text-center">
                <h3>What is BITSA?</h3>
                
                <p> We are the student body representing and supporting the Information Systems undergraduate students of UNSW's Australian School of Business. </p>                                                  
                <p> We connect students to alumni and industry sponsors as well as across all the different years currently studying at UNSW.</p>

                <p> Simply join our group at SpArc to be recognised as an official BITSA member for insights into the technology industry and networking opportunities. </p>

                <div class="slider-button">
                     <a class="slide-btn" href="https://member.arc.unsw.edu.au/s/clubdetail?clubid=0016F0000371VwQQAU">GET INVOLVED</a>
                </div>

            </div>
        </div>
    </div>        
</div>  
{% endblock %}